### ISSUE TITLE
 앱서버에서 GCM 서버로 메시지 전달할때 옵션변경

### ISSUE THREAD

**Issue by JHHJYJ** [jinwonchoi/ringcatcher#3]
현재 Notification Message 로 전달하고 있음.
이렇게 하면 앱이 종료되거나 Background 로 있으면 
 내부 GcmListnerService 의 onMessageReceived() 를 받지 못함.
즉, 폰은 메시지를 받는데 앱에 전달이 되지 않음.
그래서 Data Message 로 변경에서 GCM 서버에 보내야 됨.
아래 링크 참고..

http://stackoverflow.com/questions/35257410/how-to-customize-notification-display-and-tone-when-using-gcmreceiver-and-gcmlis/35368530#35368530

**So there are two kinds of GCM messages:**
**Notification Messages** - these are intended to generate a notification with no intermediate processing by the application. They only hit onMessageReceived if the app is running.

**Data Messages** - these are intended to silently pass data to the app's messaging service. They hit onMessageReceived even if the app is in the background. The service may then choose to generate a notification using the normal system notification APIs, or it may choose to handle the message silently.

**Comment by jinwonchoi** [comment]
노티에 뜨면 클릭할때 반영하는걸로 생각해서 그걸로만 처리했는데
사용자가 노티를 클릭안하는 경우도  고려해야겠네요. 
반영해두겠습니다.

**Comment by jinwonchoi** [comment]
확인해보니 data, notification둘 다 값을 넣어서 보내고 있습니다.
service에서 data를 받도록 되어있을겁니다.

지금 작업 끝나는대로 저도 따로 테스트 해볼텐데..
service가 background일때 받는지 확인 좀 부탁드립니다.

```
    public boolean call(Object data, String tokenId, String callingNum, String callingName, String locale) {
        boolean result = false;
        try {
            // Prepare JSON containing the GCM message content. What to send and where to send.
            JSONObject jGcmData = new JSONObject();
            JSONObject jData = new JSONObject();
            jData.put("message", data);
            // Where to send GCM message.
            // What to send in GCM message.
            jGcmData.put("data", jData);
            JSONObject jNoti = new JSONObject();
            if (Locale.KOREA.toString().equals(locale)) {
                jNoti.put("body", "어플에서 확인하세요.");
                jNoti.put("title", String.format("<%s>(%s)님이 벨소리 변경을 요청하셨습니다.", callingName,callingNum));
                jNoti.put("icon", "myicon");
            } else {
                jNoti.put("body", "Find out your Ringcatcher's updates.");
                jNoti.put("title", String.format("<%s>(%s) wants you to change his ringtone.", callingName,callingNum));
                jNoti.put("icon", "myicon");
            }
            // Create connection to send GCM Message request.
            jGcmData.put("to", tokenId);
            jGcmData.put("notification", jNoti);
```

**Comment by JHHJYJ** [comment]
테스트를 해보니

현재  Notification 으로 설정되어 넘어옵니다.
백그라운드에서 정상 수신이 되지 않습니다.

On Mon, Jun 13, 2016 at 1:44 AM, Jesse Jinwon Choi <notifications@github.com
